# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ribocentre aptamer
email: rnapuzzles@gzlab.ac.cn
description: > # this means to ignore newlines until "baseurl:"
  Ribocentre-aptamer is a database of RNA aptamers.
baseurl: ""
url: ""

# Release download configuration for colored structures
repo_owner: RNA-Aptamer-Database
repo_name: Ribocentre-aptamer.github.io
colored_structures_release_tag: 20250907-1

include:
  - .htaccess
  - _pages
  - _posts
  - search.json

sass:
  sass_dir: _sass

plugins:
  # - jekyll-archives
  - liquid
  - jekyll-sitemap

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives:
  # enabled:
    # - categories
    # - tags
  # layout: 'archive'
  # permalinks:
    # category: '/category/:name/'
    # tag: '/tag/:name/'
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

